# Generated by Django 3.2.3 on 2021-06-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_zapatilla_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapatilla',
            name='foto',
            field=models.ImageField(null=True, upload_to='Zapas', verbose_name='Foto de Zapatilla'),
        ),
    ]
