# Generated by Django 3.2.3 on 2021-06-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_zapatilla_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='estado',
            field=models.IntegerField(default=0, verbose_name='Estado de la direccion'),
            preserve_default=False,
        ),
    ]
